version: "3.8"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - frontend_network
      - backend_network

  frontend:
    build: frontend/
    expose:
      - 3000
    networks:
      - frontend_network

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
      args:
        UPLOADS_PATH: /var/uploads
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/db
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - backend_network
    restart: unless-stopped

  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # Don't use this password in production
      - POSTGRES_DB=db
    expose:
      - 5432
    networks:
      - backend_network

networks:
  frontend_network:
  backend_network:
